spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3308/photoPlusDB?useSSL=false&serverTimezone=UTC
    username: root
    password:

server:
  port: 8090

logging:
  level:
    pl:
      polsl:
        photoplus: debug

photoplus:
  pageSize: 20

