spring:
  profiles:
    active: "dev"
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    pl:
      polsl:
        photoplus: debug

photoplus:
  pageSize: 20

  securitySecret: 8N13^lM7wOI^c@2jaell6M#$zM703SL47#rY0UUo6wp344VYroSdGloYB3ff%yi8$SOqivz$C#hjU*gjRPEUrA&46UO0C5pgM3J
  #5 hours
  securityExpiration: 18000000
  securityHeaderName: Authorization
  securityTokenPrefix: "Bearer "

---

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/photoPlusDB?useSSL=false&serverTimezone=UTC
    username: root
    password: pass

server:
  port: 8090

---

spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://mysqlPP:3306/photoPlusDB?useSSL=false&serverTimezone=UTC
    username: root
    password: root

server:
  port: 9020
